branches:
 only:
  - master
  - /^ci.*$/

# Build worker image (VM template)
image: Visual Studio 2017

platform:
  - x86

configuration:
  - Release

cache:
  - '%USERPROFILE%\ExternalData'

environment:
  global:
    CYG_ROOT: C:\cygwin

  matrix:
    - GENERATOR: "Visual Studio 14 2015"
    - GENERATOR: "Visual Studio 15 2017"


build_script:
  - mkdir build & cd build & cmake -G "%GENERATOR%" -A x64 .. & cmake --build .

test: off

deploy: off
