branches:
 only:
  - master
  - /^ci.*$/

platform:
  - x86

configuration:
  - Release

cache:
  - '%USERPROFILE%\ExternalData'

environment:
  global:
    CYG_ROOT: C:\cygwin

  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 15 2017 Win64"


build_script:
  - mkdir build & cd build & cmake -G "%GENERATOR%" .. & cmake --build .

test: off

deploy: off
